openapi: "3.0.1"
info:
  title: "Banking System API"
  description: "Banking System API"
  version: "1.0.0"
servers:
  - url: "http://localhost:8080/api"
    description: "Development Server"
paths:
  /users:
    get:
      tags:
        - "User Management"
      summary: "Get all users"
      description: "Retrieve a list of all users"
      operationId: "getAllUsers"
      responses:
        "200":
          description: "Successfully retrieved users"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserResponse"
        "500":
          description: "Internal server error"

components:
  schemas:
    UserResponse:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
        age:
          type: integer
        monthlyIncome:
          type: number
          format: double
        creditScore:
          type: integer
        role:
          type: string
          enum: [ADMIN, USER, EMPLOYEE]
        accounts:
          type: array
          items:
            $ref: "#/components/schemas/AccountResponse"

    AccountResponse:
      type: object
      properties:
        accountId:
          type: integer
          format: int64
        balance:
          type: number
          format: double
        status:
          type: string
          enum: [ACTIVE, BLOCKED]
        userId:
          type: integer
          format: int64
          nullable: true
        userName:
          type: string
          nullable: true